namespace:
  name: sandbox
 
image:
  repository: tupo215/techtrends 
  tag: latest
  pullPolicy: IfNotPresent

replicaCount: 1

containerPort: 3111

service:
  port: 4111
  targetPort: 3111
  protocol: TCP
  type: ClusterIP

resources:
  requests:
    memory: "64Mi"
    cpu: "250m"
  limits:
    memory: "128Mi"
    cpu: "500m"