namespace:
  name: prod

image:
  repository: tupo215/techtrends 
  tag: latest
  pullPolicy: Always 

replicaCount: 3

containerPort: 3111



service:
  port: 7111
  targetPort: 3111
  protocol: TCP
  type: ClusterIP

resources:
  requests:
    memory: "128Mi"
    cpu: "350m"
  limits:
    memory: "256Mi"
    cpu: "500m"