name: TechTrends - Package with Docker

on:
  push:
    branches:
      - 'master'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - 
        name: Build image
        uses: docker/build-push-action@v2.7.0
        with:
          tags: tupo215/techtrends:latest 
          file: ./project/Dockerfile
      -
        name: Build and push Docker images
        uses: docker/build-push-action@v2.7.0
        with:
          context: ./project/Dockerfile
          push: true
          tags: tupo215/techtrends:latest
